name: 'install dependencies'
description: 'installs project dependencies using pnpm'

inputs:
  frozen-lockfile:
    description: 'whether to use --frozen-lockfile flag'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.frozen-lockfile }}" = "true" ]; then
          # pnpm install --frozen-lockfile
          pnpm install
        else
          pnpm install
        fi
