---

- name: deploy kibamail application
  hosts: app
  become: true

  pre_tasks:
    - name: validate deploy_tag is provided
      fail:
        msg: "deploy_tag is required. Please provide a valid git tag with --extra-vars 'deploy_tag=v1.0.0'"
      when: deploy_tag is not defined or deploy_tag == ""

    - name: validate infisical_service_token is provided
      fail:
        msg: "infisical_service_token is required. Please provide a valid token with --extra-vars 'infisical_service_token=your_token'"
      when: infisical_service_token is not defined or infisical_service_token == ""

    - name: display deployment information
      debug:
        msg:
          - "deploying kibamail"
          - "tag: {{ deploy_tag }}"
          - "hosts: {{ ansible_play_hosts | join(', ') }}"

  roles:
    - deploy

  post_tasks:
    - name: display deployment status
      debug:
        msg: "deployment completed on {{ inventory_hostname }}"
