---
- name: install required system packages
  hosts: app
  become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install build dependencies
      apt:
        name:
          - build-essential
          - python3
          - g++
          - make
        state: present

- name: setup nodejs environment
  hosts: app
  become: false
  roles:
    - nodejs

- name: setup nginx reverse proxy
  hosts: app
  become: true
  vars:
    nginx_port: 80
  roles:
    - nginx
