services:
  monolith:
    container_name: monolith
    build:
      context: ..
      dockerfile: docker/app.dockerfile
    ports:
      - "5566:5566"
    depends_on:
      - mysql
      - redis
      - kumomta-dev
    environment:
      - INFISICAL_ENV=coder
    volumes:
      - ..:/app
      - /app/node_modules
    networks:
      default:
        ipv4_address: 172.20.0.165
