services:
  pebble:
    image: ghcr.io/letsencrypt/pebble:latest
    command: -config test/config/pebble-config.json -strict false -dnsserver 172.20.0.105:8053
    ports:
      - 14000:14000 # HTTPS ACME API
      - 15000:15000 # HTTPS Management API
    environment:
      - PEBBLE_VA_NOSLEEP=1
      - PEBBLE_VA_ALWAYS_VALID=1
    networks:
      default:
        ipv4_address: 172.20.0.100
  challtestsrv:
    image: ghcr.io/letsencrypt/pebble-challtestsrv:latest
    command: -defaultIPv6 "" -defaultIPv4 172.20.0.105
    ports:
      - 8055:8055 # HTTP Management API
    networks:
      default:
        ipv4_address: 172.20.0.105
