
services:
  devcontainer:
   build:
    context: .
    dockerfile: devcontainer.dockerfile
   container_name: devcontainer
   volumes:
     - ..:/workspaces:cached
   networks:
     default:
       ipv4_address: 172.20.0.175
