name: 'setup node and pnpm'
description: 'Sets up Node.js and PNPM with caching'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  pnpm-version:
    description: 'PNPM version'
    required: false
    default: '9'

runs:
  using: 'composite'
  steps:
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-cache-store-