---

- name: restart redis
  systemd:
    name: "{{ redis_service_name }}"
    state: restarted
    daemon_reload: yes

- name: reload redis
  systemd:
    name: "{{ redis_service_name }}"
    state: reloaded
