name: end to end tests tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  server-tests:
    name: end to end tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/setup-docker

      - uses: ./.github/actions/run-command
        with:
          name: run end to end tests with coverage
          command: |
            pnpm exec playwright install
            pnpm test:e2e
