name: server tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  server-tests:
    name: server tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/setup-docker

      - uses: ./.github/actions/run-command
        with:
          name: run server tests with coverage
          command: pnpm test:server:coverage
